server:
  port: 4003

spring:
  application:
    name: NOTIFICATION-SERVICE
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:3000/./databases/notification-db
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect : org.hibernate.dialect.H2Dialect
  mail:    host: localhost
    username: info@notification.com
    password: info
    properties:      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
      mail.smtp.auth: true
  batch:    job:      enabled: false