server:
  port: 4001
  
spring:
  application:
    name: PART-MAINTENANCE-SERVICE
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:3000/./databases/VEHICLE_MAINTENANCE_TASK
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect : org.hibernate.dialect.H2Dialect
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
