server:
  port: 4000
  
spring:
  application:
    name: PART-SCHEDULE-REFRENCE-SERVICE
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:3000/./databases/vechile-list
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect : org.hibernate.dialect.H2Dialect
